### ISSUE TITLE
Not a bug report, just a thank you.

### ISSUE THREAD

**Issue by Denslat** [ton185/MinableAtmOres#1]
Just wanted to say you are an absolute legend, after struggling to do this myself I ended up dropping every bit of google fu I knew only to fail... I then asked chatgpt to help which did not, then I asked it to scour the internet and voila here i am after testing this in game, thanking the gods that this exists because fuck the allthemods author, at least give us a god damn toggle.

**Comment by ton185** [comment]
Thank you, it feels very nice when I learn that someone actually found my mod useful :smile: 
Enjoy!
